# Generated by Django 5.1.7 on 2025-03-18 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cake/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('isDiscount', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('finalPrice', models.DecimalField(decimal_places=3, max_digits=8)),
                ('info_number', models.TextField()),
                ('is_cake_of_day', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
