# Generated by Django 5.1.7 on 2025-03-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cake_finalprice_alter_cake_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='finalPrice',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
