# Generated by Django 5.1.7 on 2025-03-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cake_finalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='finalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='isDiscount',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
