# Generated by Django 5.1.7 on 2025-03-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cake_finalprice_alter_cake_isdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='finalPrice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='isDiscount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
