# Generated by Django 5.1.7 on 2025-03-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_cake_finalprice_alter_cake_isdiscount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='is_cake_of_day',
            new_name='isCake_ofDay',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='finalPrice',
        ),
        migrations.AlterField(
            model_name='cake',
            name='info_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cake',
            name='isDiscount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
