# Generated by Django 5.1.7 on 2025-03-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_is_cake_of_day_cake_iscake_ofday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='isCake_ofDay',
            new_name='isCake',
        ),
    ]
