# Generated by Django 5.1.7 on 2025-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_iscake_ofday_cake_iscake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='info_number',
            field=models.IntegerField(verbose_name=[]),
        ),
        migrations.AlterField(
            model_name='cake',
            name='isDiscount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
