# Generated by Django 5.1.7 on 2025-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_cake_info_number_alter_cake_isdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='info_number',
            field=models.IntegerField(),
        ),
    ]
