# Generated by Django 5.1.7 on 2025-03-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_cake_info_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='info_number',
            field=models.JSONField(default=list),
        ),
    ]
