# Generated by Django 5.1.7 on 2025-03-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_cake_info_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='isCake',
        ),
        migrations.AddField(
            model_name='category',
            name='countProducts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='cake/'),
            preserve_default=False,
        ),
    ]
